[ObsGraphFlaskApp]
# Main configuration for ObsGraph Flask application
salt = 9848325356041712 # Application salt value
observium_api_url = "" # Observium API URL
api_login = "" # Observium API login
api_password = "0qPSqNKh0pTSp9Kl0q3SpQ==" # Observium API password
# -----<end of section: 'ObsGraphFlaskApp'>-----
