[ObsGraphFlaskApp]
# Main configuration for ObsGraph Flask application
salt = 9848325356041712 # Application salt value
observium_api_url = "https://observium.bioseco.com/" # Observium API URL
api_login = "api" # Observium API login
api_password = "0rPStdON0qHSo9K304DTh9ON0pHSq9ON04DSo9Ky0pM=" # Observium API password
# -----<end of section: 'ObsGraphFlaskApp'>-----
