[ObsGraphFlaskApp]
# Main configuration for ObsGraph Flask application
salt = 5083235041753769 # Application salt value
observium_url = "https://observium.bioseco.com/" # Observium API URL
api_login = "api" # Observium API login
api_password = "yL7JgM26yKzIrsmCyYvNss26yJzIts26yYvIrsi9yJ4=" # Observium API password (encrypted)
# Main configuration for ObsGraph Flask application
# -----<end of section: 'ObsGraphFlaskApp'>-----
